[project]
name = "college-alg-2-bbf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
]
